// <auto-generated />
using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using GalaViewModelBase = GalaSoft.MvvmLight.ViewModelBase;
using GalaSoft.MvvmLight.Ioc;
using Microsoft.Practices.ServiceLocation;


namespace LaserPi.ViewModel {
	[GeneratedCode("T4ViewModelLocator", "1.0"), DebuggerNonUserCode]
	public class ViewModelLocator {
  		public ViewModelLocator() {
			ServiceLocator.SetLocatorProvider(() => SimpleIoc.Default);
			SimpleIoc.Default.Register<MainViewModel>();
		}

	  	public static void Cleanup() {
			ClearMainViewModel();
		}

		#region MainViewModel

        /// <summary>
        /// Gets the MainViewModel property.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Justification = "This non-static member is needed for data binding purposes.")]
        public MainViewModel Main {
            get
            {
				return ServiceLocator.Current.GetInstance<MainViewModel>();
            }
        }

        /// <summary>
        /// Provides a deterministic way to delete the MainViewModel property.
        /// </summary>
        public static void ClearMainViewModel() {
			ServiceLocator.Current.GetInstance<MainViewModel>().Cleanup();
        }

		#endregion

	}
}
